# foundry.toml (FINAL - Mainnet Optimized)

[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
cache_path = 'cache'
solc_version = '0.8.28'
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 20000
via_ir = true
gas_reports = ["*"]
verbosity = 3
bytecode_hash = "none"
fs_permissions = [{ access = "read-write", path = "./"}]
# gas_limit = 8000000      # <<< CHANGE: Increased base limit for complex deployments
timeout = 300            # <<< CHANGE: Increased RPC timeout to 5 minutes

remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/"
]

[fuzz]
runs = 1000
max_test_rejects = 100000

[profile.ci]
fuzz_runs = 10000

[profile.gas]
via_ir = true
optimizer = true
optimizer_runs = 20000

[rpc_endpoints]

bsc = "${MAINNET_RPC_URL}"
bsc_fallback = "https://bsc-dataseed1.ninicoin.io/"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"

[etherscan]

bsc = { key = "${BSCSCAN_API_KEY}", chain = 56, url = "https://api.bscscan.com/api" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}", chain = 97, url = "https://api-testnet.bscscan.com/api" }

[fmt]
line_length = 120
multiline_func_header = 'attributes_first'
quote_style = 'double'