[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
cache_path = 'cache'
solc_version = '0.8.28'
evm_version = 'paris'
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
verbosity = 3
bytecode_hash = "none"

remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/"
]

[fuzz]
runs = 1000
max_test_rejects = 100000

[profile.ci]
fuzz_runs = 10000

[profile.gas]
via_ir = true
optimizer = true
optimizer_runs = 200

# [rpc_endpoints]
# mainnet = "${MAINNET_RPC_URL}"
# bnb = "${BNB_RPC_URL}"

# [etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# bnb = { key = "${BSCSCAN_API_KEY}", chain = 97, url = "https://api-testnet.bscscan.com/api" }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
bnb = "${BNB_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}" # Add this line

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
# Let's fix the bnb key to point to bscscan testnet correctly
bsc_testnet = { key = "${BSCSCAN_API_KEY}", chain = 97, url = "https://api-testnet.bscscan.com/api" }